"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[hostname]
format = "[@$hostname]($style) "
ssh_only = true

[directory]
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = "[$branch]($style)"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)]($style) ($ahead_behind )($stashed)]($style) "
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"
ahead = "↑"
behind = "↓"
diverged = "↓↑"

[cmd_duration]
format = "[$duration]($style) "

[python]
format = "[$virtualenv]($style) "
detect_extensions = []
detect_files = []
